config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  root "home#index"
  resources :users
  resources :books
  resources :authors
  resources :categories
  resources :rentals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  has_many :categories, through: :books
  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
end

app/models/book.rb
class Book < ApplicationRecord
  extend FriendlyId
  belongs_to :author
  belongs_to :category
  has_many :rentals

  validates :title, presence: true
  friendly_id :title, use: :slugged

  def available?
    !is_rented
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validate :book_availability

  before_create :set_rented_at
  before_update :set_returned_at

  private

  def book_availability
    erros.add(:book, "is already rented") unless book.available?
  end

  def set_rented_at
    self.rented_at = Time.now
  end

  def set_returned_at
    if returned_at_changed? && returned_at.present?
      book.update(is_rented: false)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  has_many :rentals
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true
  friendly_id :name, use: [ :slugged, :history ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[show edit update destroy]
  skip_before_action :verify_authenticity_token

  def index
    @authors = Author.all
  end

  def show; end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to @author, notice: "Author was created"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @author.update(author_params)
      redirect_to @author, notice: "Author was updated"
    else
      render :edit
    end
  end

  def destroy
    @author.destroy
    redirect_to authors_path, notice: "Author was deleted"
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_book, only: %i[show edit update destroy]
  before_action :set_authors, only: %i[new edit create]

  def index
    @books = Book.includes(:author).all
  end

  def show
  @book = Book.friendly.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: "Book was created"
    else
      puts @book.errors.full_messages
      render :new
    end
  end


  def edit
    @book = Book.friendly.find(params[:id])
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: "Book was updated"
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: "Book was deleted"
  end

  private

  def set_book
    @book = Book.friendly.find(params[:id])
  end

  def set_authors
    @authors = Author.all
  end

  def book_params
    params.require(:book).permit(:title, :description, :release_date, :author_id, :category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: "Category was created"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: "Category was updated"
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: "Category was deleted"
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController\
  # before_action :set_rental, only: %i[show edit update destroy]
  # before_action :set_users_and_books, only: %i[new edit]
  before_action :set_book, only: [ :new, :create ]

  def index
    @books = Book.where(is_rented: false)
  end

  def show; end

  def new
    @rental = Rental.new
  end

  def create
   @rental = Rental.new(rental_params)
   @rental.user = current_user
   @rental.book = @book

   if @rental.save
     redirect_to rentals_path, notice: "Book rented sucessfully"
   else
    render :new
   end
  end

  def edit; end

  def update
    @rental.update(rental_params)
    if @rental.save
      redirect_to @rental, notice: "Rental successfully updated."
    else
      set_users_and_books
      render :edit
    end
  end

  def destroy
    @rental.destroy
    redirect_to rentals_path, notice: "Rental successfully removed."
  end

  private

  # def set_rental
  #   @rental = Rental.find(params[:id])
  # end

  # def set_users_and_books
  #   @users = User.all
  #   @books = Book.all
  # end

  def set_book
    puts "Book ID: #{params[:book_id]}"
    @book = Book.friendly.find(params[:book_id])
  end

  def rental_params
    params.require(:rental).permit(:book_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [ :create ]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: { id: @user.id, name: @user.name, email: @user.email, slug: @user.slug }, status: :created
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.friendly.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to new_user_path, notice: "Usuário excluído."
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/edit.html.erb
<h1>Hello, World!</h1>
<p>Welcome to the Authors Edit Page</p>

app/views/authors/index.html.erb
<h1>Lista de Livros</h1>

<table>
  <thead>
    <tr>
      <th>Título</th>
      <th>Autor</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author.name %></td>
        <td>
          <%= link_to "Ver", book_path(book) %> |
          <%= link_to "Editar", edit_book_path(book) %> |
          <%= link_to "Excluir", book, method: :delete, data: { confirm: "Tem certeza?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/authors/new.html.erb
<h1>Hello, World!</h1>
<p>Welcome to the Authors New Page</p>

app/views/authors/show.html.erb
<h1>Hello, World!</h1>
<p>Welcome to the Authors Show Page</p>

app/views/books/_form.html.erb
<%= form_with model: book do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :release_date %>
    <%= form.date_field :release_date %>
  </div>

  <div>
    <%= form.label :author_id %>
    <%= form.collection_select :author_id, Author.all, :id, :name %>
  </div>

  <div>
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render "form", book: @book %>

<%= link_to "Cancel", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Published Date</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author.name %></td> <!-- Corrigido para exibir o nome do autor -->
        <td><%= book.release_date %></td>
        <td>
          <%= link_to 'Show', book %> |
          <%= link_to 'Edit', edit_book_path(book) %> |
          <%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render "form", book: @book %>

<%= link_to "Cancel", books_path %>

app/views/books/show.html.erb
<div>
  <h1><%= @book.title %></h1>
<p><strong>Author:</strong> <%= @book.author.name %></p>
<p><strong>Description:</strong> <%= @book.description %></p>
<p><strong>Release Date:</strong> <%= @book.release_date %></p>
<p><strong>Category:</strong> <%= @book.category.name %></p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>
</div>

app/views/categories/edit.html.erb
<h1>Hello, World!</h1>
<p>Welcome to the Categories Edit Page</p>

app/views/categories/index.html.erb
<h1>Hello, World!</h1>
<p>Welcome to the Categories Index Page</p>

app/views/categories/new.html.erb
<h1>Hello, World!</h1>
<p>Welcome to the Categories New Page</p>

app/views/categories/show.html.erb
<h1>Hello, World!</h1>
<p>Welcome to the Categories Show Page</p>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library Home</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header">
    <h1 class="title">Welcome to the Library</h1>
    <nav>
      <div> 
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Books', books_path %></li>
        <li><%= link_to 'Authors', authors_path %></li>
        <li><%= link_to 'Categories', categories_path %></li>
      </ul>
      </div>
    </nav>
  </header>

  <div>
    <h2>Explore our collection of books</h2>
    <p>Find your next great read among thousands of titles available in our digital library.</p>
    

    <div>
      <%= link_to 'Ver livros', books_path, class: "btn" %>
      <%= link_to 'Adicionar um livro novo', new_book_path, class: "btn" %>
    </div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Library App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application', media: 'all' %>
<%= stylesheet_link_tag 'home', media: 'all' if controller_name == 'home' && action_name == 'index' %>

   
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rentals/edit.html.erb
<h1>Hello, World!</h1>
<p>Welcome to the Rentals Edit Page</p>

app/views/rentals/index.html.erb
<h1>Available Books</h1>

<% @books.each do |book| %>
  <div>
    <h2><%= book.title %></h2>
    <p><%= book.description %></p>
    <%= link_to 'Rent', new_rental_path(book_id: book.id) %>
  </div>
<% end %>

app/views/rentals/new.html.erb
<h1>Rent <%= @book.title %></h1>

<%= form_with model: @rental, url: rentals_path do |form| %>
  <%= form.hidden_field :book_id, value: @book.id %>
  <%= form.submit 'Confirm Rental' %>
<% end %>

app/views/rentals/show.html.erb
<h1>Hello, World!</h1>
<p>Welcome to the Rentals Show Page</p>

app/views/users/edit.html.erb
<h1>Editar Perfil</h1>

<%= form_with(model: @user, url: user_path(@user), method: :patch) do |form| %>
  <p>
    <%= form.label :name, "Nome" %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :email, "E-mail" %><br>
    <%= form.email_field :email %>
  </p>

  <p>
    <%= form.submit "Atualizar" %>
  </p>
<% end %>

app/views/users/index.html.erb
<h1>Hello, World!</h1>
<p>Welcome to the User Index Page</p>

app/views/users/new.html.erb
<h1>Cadastro de Usuário</h1>

<%= form_with(model: @user, url: users_path, method: :post) do |form| %>
  <p>
    <%= form.label :name, "Nome" %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :email, "E-mail" %><br>
    <%= form.email_field :email %>
  </p>

  <p>
    <%= form.label :password, "Senha" %><br>
    <%= form.password_field :password %>
  </p>

  <p>
    <%= form.submit "Cadastrar" %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1>Perfil de <%= @user.name %></h1>

<p><strong>Email:</strong> <%= @user.email %></p>

<p>
  <%= link_to "Editar Perfil", edit_user_path(@user) %> |
  <%= link_to "Excluir Conta", @user, method: :delete, data: { confirm: "Tem certeza?" } %>
</p>